version: "3.8"

services:
    app:
      build: .
      volumes: 
        - .:/projeto_moviebox
      ports:
        - 8000:8000
      image: app:project
      container_name : moviebox_container
      command: python3 manage.py runserver 